### ISSUE TITLE
PK and SK interfaces (along with gsi's) only allows string keys

### ISSUE THREAD

**Issue by ghbuck** [symphoniacloud/dynamodb-entity-store#2]
Whereas Dynamo allows two other types:

<img width="198" alt="image" src="https://github.com/symphoniacloud/dynamodb-entity-store/assets/67022940/52846560-bf39-4fb1-951b-c8364c4633ed">

Could we update to allow all three available key types?

Thanks!

**Comment by mikebroberts** [comment]
Thanks! I'll take a look to see whether I can do this fairly simply and not make typing too loose in the cases where a string is being used.

**Comment by ghbuck** [comment]
FWIW I simply added ` | number` to pk and sk in `Entity` and `GsiGenerators`.  It works for what I need. The check for a binary type would be more involved, I would assume.

**Comment by mikebroberts** [comment]
Fixed in v1.1.0 . I noticed that there was a useful type in the DynamoDB library that could handle this. Thanks again.
