### ISSUE TITLE
How to define Limit in a Query operation

### ISSUE THREAD

**Issue by cyberworkz** [symphoniacloud/dynamodb-entity-store#3]
Hi, 

DynamoDB Entity Store seems very promising. Thanks for all the documentation and examples, which do offer a good intro in this library. 

One question, I can not seem to find how you can define the 'Limit' parameter in a Query operation. How can one use this parameter with this library?

**Comment by mikebroberts** [comment]
Hi @cyberworkz  - thanks for the comments!

To use a limit use one of the “onepage” query functions, and set a limit in the options. E.g. https://github.com/symphoniacloud/dynamodb-entity-store/blob/main/documentation/SingleEntityTableQueriesAndTableScans.md#query-one-page-by-partition-key
