### ISSUE TITLE
ReturnValues on Update of an entity?!

### ISSUE THREAD

**Issue by cyberworkz** [symphoniacloud/dynamodb-entity-store#4]
Hi, how do set the 'ReturnValues on an update of an entity?

**Comment by cyberworkz** [comment]
found it, it is in the advanced operations.

**Comment by obazoud** [comment]
Same question with Delete.
`advancedOperations.delete` does not return the item.

**Comment by mikebroberts** [comment]
> Same question with Delete. `advancedOperations.delete` does not return the item.

Hi @obazoud . If you're using advancedOperations you can get the raw / unparsed version of the item - see https://github.com/symphoniacloud/dynamodb-entity-store/blob/main/documentation/AdvancedSingleEntityOperations.md#return-values-for-write-operations - but there is no current functionality in entity store to return the parsed item during a delete.
