### ISSUE TITLE
GSI based on existing columns

### ISSUE THREAD

**Issue by obazoud** [symphoniacloud/dynamodb-entity-store#6]
Hello,

Let's say I have a table with a PK, SK and a column created_at for example.
In Dynamodb, I created a GSI with PK = PK et SK = created_at

Is there a query this GSI and I don' want to generate GSIPK+GSISK columns (because I don't need it in my case) ?

Thanks

**Comment by mikebroberts** [comment]
Yep, that's fine - Table Keys and GSI Keys can share attributes. Your config would look something like:
```
myTableConfig.metaAttributeNames.gsisById = {
  gsi1: {
    pk: 'PK',
    sk: 'created_at'
  }
}
```

**Comment by obazoud** [comment]
Hello,

I think it is what I did but I got an error:
 `Error: Entity type xxx has no GSIs, and therefore cannot be queried by GSI`
when I call queryAllWithGsiByPkAndSk.

Any ideas ?

**Comment by mikebroberts** [comment]
Did you also setup your Entity for GSIs? https://github.com/symphoniacloud/dynamodb-entity-store/blob/main/documentation/GSIs.md#coding-your-entities-to-use-gsis
